export const CONTACTS = {
    SET_ALL_CONTACTS:"SET_ALL_CONTACTS",
    SET_ON_PLATFORM_CONTACTS:"SET_ON_PLATFORM_CONTACTS",
    ONLINE_CONTACT:"ONLINE_CONTACT"
}


export const CONVERSATIONS = {
    SET_ALL_CONVERSATIONS:"SET_ALL_CONVERSATIONS",
    SEND_MESSAGE:"SEND_MESSAGE",
    SEND_SINGLE_CONVERSATIONS:"SEND_SINGLE_CONVERSATIONS",
    SET_SINGLE_CONVERSATIONS:"SET_SINGLE_CONVERSATIONS",
    SINGLE_CONVERSATIONS_SET_SINGLE_MESSAGE:"SINGLE_CONVERSATIONS_SET_SINGLE_MESSAGE",
    CLEAR_SINGLE_CONVERSATION:"CLEAR_SINGLE_CONVERSATION",
    SET_LAST_MESSAGE:"SET_LAST_MESSAGE",
    SET_SINGLE_CONVERSATION_PLUS_SET_FIRST_MESSAGE:"SET_SINGLE_CONVERSATION_PLUS_SET_FIRST_MESSAGE",
    SET_SINGLE_CONVERSATION_TEMP_MESSAGE_UPDATE:"SET_SINGLE_CONVERSATION_TEMP_MESSAGE_UPDATE",
    SET_SINGLE_CONVERSATION_TEMP_MESSAGE_STATUS_UPDATE:"SET_SINGLE_CONVERSATION_TEMP_MESSAGE_STATUS_UPDATE",
    SET_SINGLE_CONVERSATION_TEMP_MESSAGE_LAST_MESSAGE:"SET_SINGLE_CONVERSATION_TEMP_MESSAGE_LAST_MESSAGE",
}


export const AUTH = {
    SET_CURRENT_USER:"SET_CURRENT_USER"
}


export const CLEAR_REDUX = {
    CLEAR_REDUCER:"CLEAR_REDUCER"
}